model:
  name: lstm
  input_dim: 6
  hidden_dim: 128
  num_layers: 2
  dropout: 0.1

optimizer:
  name: adam
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0
  eps: 1e-8

training:
  batch_size: 64
  num_epochs: 50
  early_stopping_patience: 5
  seed: 42

dataset:
  path: data/av2/train.pkl
  num_workers: 4

run_dir: runs/base   # overwritten by grid search