model:
  name: lstm

optimizer:
  name: adam
  lr: [0.0005, 0.001, 0.005]
  beta1: [0.8, 0.85, 0.9, 0.95]
  beta2: 0.999
  weight_decay: [0.0, 1e-5, 1e-4, 1e-3]

training:
  epochs: 10
  patience: 10
  seed: 42