model:
  name: lstm

optimizer:
  name: adam
  lr: 0.001
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0

training:
  epochs: 100
  patience: 10
  seed: 42

run_dir: model_outs/test/   # overwritten by grid search